name: Dev deploy

on:
  push:
    branches:
      - dev
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  main-ui:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          target: wasm32-unknown-unknown
          toolchain: stable

      - uses: cargo-bins/cargo-binstall@main

      - name: Install dioxus-cli
        run: |
          cargo binstall dioxus-cli --version 0.6.1
          cargo binstall toml-cli

      - name: Cache builder
        id: main-ui-build-cache
        uses: actions/cache@v3
        with:
          key: main-ui-build-cache
          path: |
            target

      - name: Cache builder
        id: main-ui-artifacts
        uses: actions/cache@v3
        with:
          key: main-ui-artifacts
          path: |
            .build/main-ui


      - name: Checking violate
        env:
          REGION: ap-northeast-2
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVICE: main-ui
        run: |
          dx check -p $SERVICE

      # - name: Deploy APIs
      #   env:
      #     MAIN_API_ENDPOINT:
      #     DOMAIN:

      #     REGION: ap-northeast-2
      #     ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     FIREBASE_API_KEY: "${{ secrets.FIREBASE_API_KEY }}"
      #     FIREBASE_AUTH_DOMAIN: "${{ secrets.FIREBASE_AUTH_DOMAIN }}"
      #     FIREBASE_PROJECT_ID: "${{ secrets.FIREBASE_PROJECT_ID }}"
      #     FIREBASE_STORAGE_BUCKET: "${{ secrets.FIREBASE_STORAGE_BUCKET }}"
      #     FIREBASE_MESSAGING_SENDER_ID: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}"
      #     FIREBASE_APP_ID: "${{ secrets.FIREBASE_APP_ID }}"
      #     FIREBASE_MEASUREMENT_ID: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
      #     ENV: dev
      #     SERVICE: main-ui
      #     API_PREFIX: /api
      #     ENABLE_S3: true
      #     ENABLE_FARGATE: false
      #     ENABLE_DYNAMO: true
      #     ENABLE_LAMBDA: true
      #   run: |
      #     npm i -g aws-cdk tailwindcss
      #     make deploy-web-if-needed

  main-api:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          target: wasm32-unknown-unknown
          toolchain: stable

      - uses: cargo-bins/cargo-binstall@main
      - name: Install toml-cli
        run: |
          cargo binstall toml-cli

      - name: Cache builder
        id: topic-api-build-cache
        uses: actions/cache@v3
        with:
          key: topic-api-build-cache
          path: |
            target

      - name: Cache builder
        id: topic-api-artifacts
        uses: actions/cache@v3
        with:
          key: main-api-artifacts
          path: |
            .build/main-api

      # - name: Deploy APIs
      #   env:
      #     REGION: ap-northeast-2
      #     ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     ENV: dev
      #     SERVICE: main-api
      #     DOMAIN:
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
      #     ENABLE_S3: false
      #     ENABLE_FARGATE: false
      #     ENABLE_DYNAMO: false
      #     ENABLE_LAMBDA: true
      #     ENABLE_RDS: true
      #   run: |
      #     npm i -g aws-cdk
      #     make deploy-if-needed

  create-release-pr:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    needs:
      [
        main-ui, main-api, publish-crates
      ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}
      - name: Git pr release action
        uses: grassedge/git-pr-release-action@v1.0
        with:
          base: main
          head: dev
          token: ${{ secrets.GITHUB_TOKEN }}
